name: Run tests

on:
  push:
  pull_request:
  schedule:
    - cron: '3 23 * * SUN'

permissions: {}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version:
          [
            3.2,
            3.3,
            3.4,
            jruby,
          ]
        exclude:
          - os: windows-latest
            version: jruby
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
          persist-credentials: false

      # zizmor complains that 'v1' is a ref that can be provided by both the branch and tag namespaces.
      # specify that we want the v1 branch.
      - uses: ruby/setup-ruby@d697be2f83c6234b20877c3b5eac7a7f342f0d0c # 1.269.0
        with:
          ruby-version: ${{ matrix.version }}

      - run: bundle install
        env:
          BUNDLE_FROZEN: true
      - run: bundle exec rake -t test
